kind: PersistentVolume
apiVersion: v1
metadata:
  name: k8s-pv-jenkins
  namespace: jenkins
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: jk
  hostPath:
    path: "/data/jenkins"
  persistentVolumeReclaimPolicy: Retain
